initial implementation of adding site action
kitconcept/kitconcept.voltolighttheme pull request #28
Opened 2024-01-08 15:33 UTC by iFlameing

2024-01-09 16:23 UTC, davisagli requested changes

2024-01-09 16:23 UTC, davisagli commented on src/kitconcept/voltolighttheme/profiles/default/actions.xml
> +            name="github-link"
I would just call it "github". All actions are links.

```suggestion
            name="github"
```

2024-01-09 16:23 UTC, davisagli commented on src/kitconcept/voltolighttheme/profiles/default/actions.xml
> +      >Github</property>
```suggestion
      >GitHub</property>
```

2024-01-11 14:49 UTC, sneridagh approved these changes

2024-01-11 14:49 UTC, merged