Add  Example content of Teaser-Slider Block
kitconcept/kitconcept.voltolighttheme pull request #37
Opened 2024-06-27 10:01 UTC by iRohitSingh

Fix #https://github.com/kitconcept/volto-light-theme/issues/402

2024-06-27 10:22 UTC, iRohitSingh commented
![Teaser-Slider-Block (2)](https://github.com/kitconcept/kitconcept.voltolighttheme/assets/61353484/fbbfd024-bfea-4d03-9b2a-074178c1687c)

2024-06-27 15:49 UTC, davisagli requested changes
Please stop. The old plone.distribution import/export format makes this impossible to review. There are too many changed lines to tell whether it is only making the intended change, or also other changes.

@iFlameing previously worked on this in #33 and #34 which had the same problem.

I asked for us to switch to the new plone.exportimport format because it puts each content item in a separate file. That conversion is in progress in #36 but needs more work. (I know Alok asked for help with this -- sorry I didn't find time to help yet. Maybe @ericof can.)

We need to finish switching to plone.exportimport before we try to fix anything in the actual content. Otherwise we'll likely break something each time we fix something else. /cc @sneridagh @tisto

2024-06-28 06:02 UTC, tisto commented
@davisagli thank you for brining this up! Then we should indeed first solve this problem properly before moving on.

2025-03-03 17:06 UTC, davisagli commented
We can't use this PR. The example content was updated to use the modern plone.exportimport format with separate files, and we need new PRs that use that as a base.

2025-03-03 17:06 UTC, closed without merging